# Generated by Django 4.2.1 on 2023-05-13 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Post_Type', models.CharField(max_length=225)),
                ('Post_Category', models.CharField(max_length=225)),
                ('Post_Title', models.CharField(max_length=225)),
                ('Post_Description', models.TextField()),
                ('Post_Image', models.ImageField(null=True, upload_to='post/')),
                ('Seo_Url', models.CharField(max_length=500, null=True)),
                ('Seo_Title', models.CharField(max_length=225, null=True)),
                ('Seo_Keywords', models.CharField(max_length=500, null=True)),
                ('Seo_Description', models.TextField(null=True)),
                ('AddedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Added_By', to=settings.AUTH_USER_MODEL)),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Edited_By', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
