# Generated by Django 4.2.1 on 2023-05-13 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Image', models.ImageField(upload_to='alubum_images')),
                ('AddedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.album')),
            ],
        ),
    ]
