# Generated by Django 4.2.1 on 2023-05-13 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0003_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Department_Title', models.CharField(max_length=225)),
                ('Department_Vission', models.TextField(null=True)),
                ('Department_Mission', models.TextField(null=True)),
                ('Department_Description', models.TextField(null=True)),
                ('Department_Logo', models.ImageField(null=True, upload_to='')),
                ('Department_Fecilities', models.TextField(null=True)),
                ('Department_Placement', models.TextField(null=True)),
                ('AddedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='EditedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
