# Generated by Django 4.2.1 on 2023-05-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Course_Type', models.CharField(max_length=225)),
                ('Course_Title', models.CharField(max_length=225)),
                ('Course_Subject', models.CharField(max_length=225, null=True)),
                ('Course_Complementary_Subject', models.CharField(max_length=225, null=True)),
                ('Course_Duration', models.CharField(max_length=225, null=True)),
                ('Course_Total_Seats', models.IntegerField(null=True)),
                ('Course_Syllabus', models.FileField(null=True, upload_to='syllabus')),
                ('AddedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Course_Department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.department')),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Edited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
