# Generated by Django 4.2.1 on 2023-05-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Faculty_Name', models.CharField(max_length=225)),
                ('Faculty_Designation', models.CharField(max_length=225, null=True)),
                ('Faculty_Qualification', models.CharField(max_length=225, null=True)),
                ('Faculty_Email', models.EmailField(max_length=225, null=True)),
                ('Faculty_Image', models.ImageField(null=True, upload_to='faculties')),
                ('AddedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Added', to=settings.AUTH_USER_MODEL)),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Faculty_Department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.department')),
            ],
        ),
    ]
