# Generated by Django 4.2.1 on 2023-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Seo_Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Seo_Keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Seo_Title',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Seo_Url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='Seo_Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='Seo_Keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='Seo_Title',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='Seo_Url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Seo_Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Seo_Keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Seo_Title',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Seo_Url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
