# Generated by Django 4.2.1 on 2023-05-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_course_seo_description_course_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Image',
            field=models.ImageField(blank=True, null=True, upload_to='course'),
        ),
    ]
