# Generated by Django 4.2.1 on 2023-06-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_exam_results_date_exam_results_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
