# Generated by Django 4.2.1 on 2023-06-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_news_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=225)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Academic_Qualification', models.CharField(max_length=225)),
                ('Last_Studied_Institute', models.CharField(max_length=225)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Contact_Number', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.course')),
            ],
        ),
    ]
