# Generated by Django 4.2.1 on 2023-06-13 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
