# Generated by Django 4.2.1 on 2023-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_alumni_registration_alter_admission_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_registration',
            name='Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
